### ISSUE TITLE
Add Questions for Street Prepared

### ISSUE THREAD

**Issue by Bjorn248** [Bjorn248/scca_classifier#128]

**Comment by droidttk** [comment]
Could you please provide more details about this?

**Comment by Bjorn248** [comment]
@droidttk this is a complicated issue, and I understand if you choose not to do it. This issue has two parts. The first part is to determine which questions you need to ask a user to determine if they are "bumped" out of the street prepared class due to the modifications done to their car. This involves reading the rulebook and understanding the difference between street prepared and street modified classes. Once you have a list of these "bump" questions, they need to be added to common.js as well as the HTML pages involved in asking the user those questions. You can use the street page at `a/s.html` as a template, but you will have to make `a/sp.html` as it does not currently exist. Again, I understand if you don't want to do this one as it is complicated. I mainly intended hacktoberfest participants to take on the issues with the hacktoberfest label, but I don't want to stop you from trying if you want to give it a shot.
