### ISSUE TITLE
Add all Porsche vehicles to common.js

### ISSUE THREAD

**Issue by Bjorn248** [Bjorn248/scca_classifier#13]
Find all Porsche vehicles in Appendix A of this document https://www.scca.com/downloads/49336-2020-solo-rules-complete-reduced-2020-03-16/download and add them to https://github.com/Bjorn248/scca_classifier/blob/master/common.js in a similar way to other Makes.

**Comment by 30james00** [comment]
Can I do it?

**Comment by Bjorn248** [comment]
Yes!
