### ISSUE TITLE
Add all Jensen vehicles to common.js

### ISSUE THREAD

**Issue by Bjorn248** [Bjorn248/scca_classifier#23]
Find all Jensen vehicles in Appendix A of this document https://www.scca.com/downloads/49336-2020-solo-rules-complete-reduced-2020-03-16/download and add them to https://github.com/Bjorn248/scca_classifier/blob/master/common.js in a similar way to other Makes.

**Comment by elkhorn360** [comment]
Could you please assign this to me?
