### ISSUE TITLE
Update for 2022 Rules

### ISSUE THREAD

**Issue by Bjorn248** [Bjorn248/scca_classifier#244]
Website is already outdated, find deltas and add them

- [x] New Class: Super Street Touring

**Comment by Bjorn248** [comment]
New Class: Super Street Touring

**Comment by 2yan** [comment]
Hey, 
these are some of the deltas: 
"Still has the Mustang Mach 1, and Camaro SS 1LE in B-Street, they were moved to F-Street for 2022. It's missing the new Super Street Touring (SST) Class."

**Comment by Bjorn248** [comment]
@2yan yep! I've got an in progress branch with a lot of the fixes already https://github.com/Bjorn248/scca_classifier/tree/issue-244-update-for-2022
