### ISSUE TITLE
Stylez

### ISSUE THREAD

**Issue by spacecowboyian** [Bjorn248/scca_classifier#261]
... with a z.. obviously.

Thinking I could toss in and make this look a bit better and maybe function tighter on a phone. Might just start with some simple CSS adjustments then proceed with some UXin'. Any concerns with that?

**Comment by Bjorn248** [comment]
> ... with a z.. obviously.
> 
> Thinking I could toss in and make this look a bit better and maybe function tighter on a phone. Might just start with some simple CSS adjustments then proceed with some UXin'. Any concerns with that?

That sounds great to me, I appreciate the help!

**Comment by Bjorn248** [comment]
Hey there @spacecowboyian, I'm going to go ahead and close this issue, looking forward to seeing your pull request!

**Comment by spacecowboyian** [comment]
I did start but never finished. I’ll dig it back up tomorrow.
