### ISSUE TITLE
2023 rules/classification

### ISSUE THREAD

**Issue by vivekisontrack** [Bjorn248/scca_classifier#262]
Hi there! Any plans to update this for the 2023 rules/classification? A lot of cars moved around (particularly in Street Prepared). I see that all that info lives in common.js. I can attempt to help but wouldn't be able to get to it until next month, so was curious if this is on your radar.

**Comment by Bjorn248** [comment]
> Hi there! Any plans to update this for the 2023 rules/classification? A lot of cars moved around (particularly in Street Prepared). I see that all that info lives in common.js. I can attempt to help but wouldn't be able to get to it until next month, so was curious if this is on your radar.

Hey there! I don't see a 2023 rulebook anywhere yet. The latest I could find was August 2022, and I recently took a pass at updating the rules for that. https://github.com/Bjorn248/scca_classifier/pull/260

That being said, if you find discrepancies, please submit a PR! Thanks!

**Comment by Bjorn248** [comment]
Based on the draft rules, there were some changes that moved non M E46s to ESP from DSP and moved M3s from BSP to DSP. I'll try to get to those changes next.

**Comment by Bjorn248** [comment]
Hey there @vivekisontrack, I made some updated for the 2023 rules. I'm hoping this covers most of the changes, but I'm sure I missed some :sweat_smile: . If you find any discrepancies feel free to submit a pull request! Closing this issue for now.
