### ISSUE TITLE
2023 Classing

### ISSUE THREAD

**Issue by RT-BRZ-SCCA** [Bjorn248/scca_classifier#275]
It appears that the tool isn't updated for 2023 classes. Specifically XS (Xtreme Street Sport) isn't aligning to current rules.

**Comment by Bjorn248** [comment]
Hey thanks for the report! I'll try to make some time this weekend to fix this.

**Comment by RT-BRZ-SCCA** [comment]
Excellent. Thank you.

**Comment by Bjorn248** [comment]
Hey there @RT-BRZ-SCCA, I just merged a PR that attempts to add the XS class. Please check out the site and let me know if this fixes what you reported.

**Comment by RT-BRZ-SCCA** [comment]
@Bjorn248 that seems to have corrected everything. Great work. It's appreciated.
