### ISSUE TITLE
XA/XB Class Minimum Weights

### ISSUE THREAD

**Issue by jkstill** [Bjorn248/scca_classifier#283]
The classifier shows minimum weights for XA/XB  as WITHOUT driver.

Just now checked the rules - XA/XB minimum weights are WITH driver.

**Comment by jkstill** [comment]
It appears this may be due to an update to the rules.

**Comment by Bjorn248** [comment]
Hey, thanks for the report! That's correct, they did update the rules to have the weights be with driver. I'll see if I can update the site tomorrow.

**Comment by Bjorn248** [comment]
https://github.com/Bjorn248/scca_classifier/pull/284 should fix this

**Comment by jkstill** [comment]
thanks!
