### ISSUE TITLE
Add disclaimer notes on main page.

### ISSUE THREAD

**Issue by RT-BRZ-SCCA** [Bjorn248/scca_classifier#287]
There have been a lot of "complaints" about mis-classing of cars that often fall into NOC (not otherwise classed) and it's causing confusion among the veteran drivers. A disclaimer about NOC cars and cars older than X years would be a good idea.

**Comment by Bjorn248** [comment]
> There have been a lot of "complaints" about mis-classing of cars that often fall into NOC (not otherwise classed) and it's causing confusion among the veteran drivers. A disclaimer about NOC cars and cars older than X years would be a good idea.

Hey! Thanks for the feedback! 

Where should the disclaimer go? What should the contents be? I have a disclaimer already that reads "Don't see your car listed? Choose "NOC (Not Otherwise Classified)" as your Make and find your class using the "Catch-All" categories." 

Looking forward to hearing back!

**Comment by Bjorn248** [comment]
Great suggestion, thanks. I'll try to make this change live tonight, and I'll ask for your feedback then 👍

**Comment by RT-BRZ-SCCA** [comment]
That's great. I've had your back on social media. Great work. You're really appreciated.

**Comment by Bjorn248** [comment]
Hey, sorry I didn't get to this tonight, but it's on my calendar for tomorrow.

**Comment by Bjorn248** [comment]
Hey there @RT-BRZ-SCCA, I submitted https://github.com/Bjorn248/scca_classifier/pull/288 to address this. Please let me know if that looks good and I'll go ahead and merge it!

**Comment by Bjorn248** [comment]
Closing this issue since the PR has been merged.
