### ISSUE TITLE
Porsche 718 GTS 4.0 Misclassed

### ISSUE THREAD

**Issue by zastruga** [Bjorn248/scca_classifier#302]
The SS -> AS reshuffle moved the 2.5L GTS down to AS, but the 4.0 stayed in SS.  Those vehicles are currently combined in the UI and incorrectly results in an AS classification.

**Comment by Bjorn248** [comment]
Hey there @zastruga thanks for the report! I've opened https://github.com/Bjorn248/scca_classifier/pull/303 to address this. Do the changes look good to you?
