### ISSUE TITLE
Corvette C8 (including Z06 and E-Ray) misclassed in CAM

### ISSUE THREAD

**Issue by bluestreakgp7** [Bjorn248/scca_classifier#304]
All versions of the Corvette C8 should not be classed in CAM-S or any other CAM class. Per the rules of CAM class, mid-engine and all-wheel-drive American cars are not allowed.

**Comment by Bjorn248** [comment]
Ah thanks for the report @bluestreakgp7, I think I've fixed this with https://github.com/Bjorn248/scca_classifier/pull/306
