### ISSUE TITLE
2017-2019 Corvette Grand Sport and 2013-2017 Dodge Viper (non-GTS, non-ACR, non-TA) misclassed

### ISSUE THREAD

**Issue by bluestreakgp7** [Bjorn248/scca_classifier#309]
Two cars that were part of the SS-AS reshuffle is also misclassed on the classification assistant. They should be in A Street.

**Comment by Bjorn248** [comment]
> Two cars that were part of the SS-AS reshuffle is also misclassed on the classification assistant. They should be in A Street.

Ah thanks! I'm going to spend a bit more time next week and check all of AS and SS since I seem to have missed a lot of cars. Do you have a good place to find a list of all the cars that moved?

**Comment by bluestreakgp7** [comment]
I just looked at the latest edition of the Solo rulebook. I tend to look over it a lot. 😅

**Comment by Bjorn248** [comment]
Hey there @bluestreakgp7 I think I fixed these issues with https://github.com/Bjorn248/scca_classifier/pull/310, please take a look at the live site when you have a chance! You might have to ctrl+shift+r to refresh for the changes to load.
