### ISSUE TITLE
Merge Subaru Impreza WRX (incl. STI) and Impreza WRX (incl. STI; excl. Type RA & 2019 STI) with WRX STI (including Special Edition)

### ISSUE THREAD

**Issue by bluestreakgp7** [Bjorn248/scca_classifier#319]
The two Impreza WRX options "Impreza WRX (incl. STI)" and "Impreza WRX (incl. STI; excl. Type RA & 2019 STI)" should be merged with the "WRX STI (including Special Edition)" option, as it seems to only apply to the STI models. I've noticed that some of the WRX owners in my region have been getting misclassed in STU (most likely due to these options in the classification assistant confusing them), while the WRX is an STH car in Street Touring.

**Comment by Bjorn248** [comment]
This has hopefully been addressed with https://github.com/Bjorn248/scca_classifier/pull/320, please let me know if that looks good :+1:

**Comment by bluestreakgp7** [comment]
Looks good!
