### ISSUE TITLE
Street Touring Category reshuffle

### ISSUE THREAD

**Issue by bluestreakgp7** [Bjorn248/scca_classifier#324]
Per the December 2024 Fastrack, please note the following changes to the Street Touring classes:

- Super Street Touring (SST) -> Leave as is
- A Street Touring (AST) -> Add as new class
- Street Touring Ultra (STU) -> rename to B Street Touring (BST)
- Street Touring Roadster (STR) -> rename to C Street Touring (CST)
- Street Touring Xtreme (STX) -> rename to D Street Touring (DST)
- Street Touring Sport (STS) -> rename to E Street Touring (EST)
- Street Touring Hatch (STH) -> rename to G Street Touring (GST)

**Comment by bluestreakgp7** [comment]
Additionally, the following vehicles have been moved to AST:
- Chrysler Crossfire (all)
- Fiat 124 Spider (2016-2020)
- Honda S2000 CR
- Mazda MX-5 Miata (2016-2024)
- Mazda Mazdaspeed Miata (2004-2005)
- Pontiac Solstice GXP
- Saturn Sky Red Line

Remove the following vehicles from SST:
- Chrysler Crossfire (all)
- Pontiac Solstice GXP
- Saturn Sky Red Line

Make the following changes to CST (formerly STR):
- Honda S2000 **(non-CR)**
- Mazda MX-5 Miata (2006-**2015**)

Remove the following vehicles from BST (formerly STU):
- Fiat 124 Spider (2016-2020)
- Mazda Mazdaspeed Miata (2004-2005)

**Comment by Bjorn248** [comment]
https://github.com/Bjorn248/scca_classifier/pull/327 should have addressed this, thanks for making the changes easy to digest @bluestreakgp7 !
