### ISSUE TITLE
Multiple class reshuffles

### ISSUE THREAD

**Issue by bluestreakgp7** [Bjorn248/scca_classifier#325]
Per the December 2024 Fastrack, please make the following changes:

Move the following vehicles from GS to HS:
- Hyundai Veloster Turbo (all) (2019-2021)
- Mini Cooper Clubman (Base 3-cyl, non-JCW) (2016-2019)
- Mini Cooper Hardtop (Base 3-cyl, non-JCW) (2014-2023)

Move the following vehicles from DS to GS:
- BMW 2 Series Gran Coupe (228i FWD) (2020-2024)
- Mini Cooper Clubman S (2016-2023)
- Mini Cooper Hardtop S (2014-2023)

Make the following change in DS:
- BMW 2 Series Gran Coupe (228i **xDrive** and M235i) (2020-**2024**)

Move the following vehicle from BS to CS:
- BMW Z4 4 cyl (2020-2024)

Move the following vehicles from SS to AS:
- Lotus Evora 400 (2016-2018)
- Lotus Evora GT (2020-2022)

Move the following vehicles from AS to DS:
- Tesla Model 3 (RWD) (2018-2024)

Make the following changes in AS:
- Tesla Model 3 (**AWD/Performance 2018-2023**)
- Tesla Model Y (**AWD/Performance 2020-2024**)

Add the following vehicle to GS:
- Mini Cooper Hardtop S (2-door and 4-door F65/F66 chassis) (2025)

Add the following vehicle to HS:
- Mini Cooper Hardtop (non-S, 2-door and 4-door F65/F66 chassis) (2025)

Move the following vehicles from EST (STS) to DST (STX)
- Honda Accord (6-cyl) (1998-2013)
- Subaru Impreza 2.5 RS (1998-2001)

Make the following change to DST (STX):
- Subaru BRZ **excl. tS** (2013-2020)

**Comment by Bjorn248** [comment]
https://github.com/Bjorn248/scca_classifier/pull/328 addresses this

**Comment by Bjorn248** [comment]
Thanks for all the help with this, and apologies for the delays on these updates
