### ISSUE TITLE
2024 Subaru WRX TR and 2025 WRX tS to D Street

### ISSUE THREAD

**Issue by bluestreakgp7** [Bjorn248/scca_classifier#329]
Per the January 2025 Fastrack, please make the following additions to D Street (DS):

- Subaru WRX TR (2024)
- Subaru WRX tS (2025)

**Comment by Bjorn248** [comment]
This should be live!

**Comment by bluestreakgp7** [comment]
Thanks! Also, side note: all other classes the standard 2022+ WRX is eligible for should also be added for the TR and tS.

**Comment by Bjorn248** [comment]
> Thanks! Also, side note: all other classes the standard 2022+ WRX is eligible for should also be added for the TR and tS.

I believe that's the case, did I miss something?
