### ISSUE TITLE
Add all Ford vehicles to common.js

### ISSUE THREAD

**Issue by Bjorn248** [Bjorn248/scca_classifier#4]
Find all Ford vehicles in Appendix A of this document https://www.scca.com/downloads/49336-2020-solo-rules-complete-reduced-2020-03-16/download and add them to https://github.com/Bjorn248/scca_classifier/blob/master/common.js in a similar way to other Makes.

**Comment by guptapranav4299** [comment]
Let me do this @Bjorn248

**Comment by guptapranav4299** [comment]
there is no year of model given in the pdf  for Ford Mustang V8 in the F Street class section....from what year should I mention ?
@Bjorn248

**Comment by Bjorn248** [comment]
'all'

**Comment by ejleitzke** [comment]
@Bjorn248 Please assign this to me!
